### PR TITLE
Log a warning if a session attribute is not serializable

### PR DESCRIPTION
**Pull request by T3rm1**
Not sure whether warning or error is appropriate.

### CODE REVIEW

**Comment by kulchytskyy** [comment]
Please don't forget about the `removeAttribute` method, which has similar try/catch.

**Comment by T3rm1** [comment]
removeAttribute does not do any serialization.

**Comment by kulchytskyy** [comment]
Ok.  Didn't notice that we catch serialization exception.

**Comment by emre-aydin** [comment]
Looks good. Can you please squash your commits into one commit? Also, could you please sign our Contributor Agreement to have the PR merged into Hazelcast repository?
https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement

**Comment by T3rm1** [comment]
Here you go.
But I'm not going to sign any document in order to contribute code on github. If that's for some strange reason a problem then please use my code and create a commit with it.

**Comment by emre-aydin** [comment]
Closing as user refused to sign the Contributor Agreement. Same code submitted as another PR here: https://github.com/hazelcast/hazelcast-wm/pull/36

**Pull request closed without merging**
